<?php

return [
    'providers' => [
        'alipay' => [
            'class' => \App\Payments\Providers\AlipayPaymentProvider::class,
            'fields' => [
                [
                    'key' => 'app_id',
                    'label' => "\u{5E94}\u{7528}ID",
                    'input' => 'text',
                    'maxlength' => 80,
                    'hint' => "\u{586B}\u{652F}\u{4ED8}\u{5B9D}\u{5F00}\u{653E}\u{5E73}\u{53F0}\u{91CC}\u{7684}\u{5E94}\u{7528}ID\u{3002}",
                ],
                [
                    'key' => 'public_key',
                    'label' => "\u{652F}\u{4ED8}\u{5B9D}\u{516C}\u{94A5}",
                    'input' => 'textarea',
                    'rows' => 5,
                    'secret' => true,
                    'hint' => "\u{8FD9}\u{91CC}\u{586B}\u{652F}\u{4ED8}\u{5B9D}\u{516C}\u{94A5}\u{FF0C}\u{4E0D}\u{662F}\u{5E94}\u{7528}\u{516C}\u{94A5}\u{3002}",
                ],
                [
                    'key' => 'private_key',
                    'label' => "\u{5E94}\u{7528}\u{79C1}\u{94A5}",
                    'input' => 'textarea',
                    'rows' => 7,
                    'secret' => true,
                    'hint' => "\u{586B}\u{5E94}\u{7528}\u{79C1}\u{94A5}\u{FF0C}\u{9700}\u{8981}\u{548C}\u{5E94}\u{7528}\u{516C}\u{94A5}\u{6210}\u{5BF9}\u{3002}",
                ],
            ],
            'payment_methods' => ['page', 'scan'],
            'payment_scenes' => ['pc', 'mobile', 'general'],
            'default_payment_method' => 'page',
            'default_payment_scene' => 'general',
        ],
        'wechat' => [
            'class' => \App\Payments\Providers\WechatPaymentProvider::class,
            'fields' => [
                [
                    'key' => 'app_id',
                    'label' => 'AppID',
                    'input' => 'text',
                    'maxlength' => 64,
                    'hint' => "\u{586B}\u{4E0E}\u{5546}\u{6237}\u{53F7}\u{7ED1}\u{5B9A}\u{7684} AppID\u{3002}",
                ],
                [
                    'key' => 'mch_id',
                    'label' => "\u{5546}\u{6237}\u{53F7}",
                    'input' => 'text',
                    'maxlength' => 64,
                    'hint' => "\u{5FAE}\u{4FE1}\u{652F}\u{4ED8}\u{5546}\u{6237}\u{53F7}\u{3002}",
                ],
                [
                    'key' => 'api_v3_key',
                    'label' => 'APIv3 Key',
                    'input' => 'text',
                    'maxlength' => 64,
                    'secret' => true,
                    'hint' => "\u{586B} APIv3 Key\u{FF0C}\u{7528}\u{4E8E}\u{56DE}\u{8C03}\u{89E3}\u{5BC6}\u{548C}\u{67E5}\u{5355}\u{9A8C}\u{8BC1}\u{3002}",
                ],
                [
                    'key' => 'serial_no',
                    'label' => "\u{5546}\u{6237}\u{8BC1}\u{4E66}\u{5E8F}\u{5217}\u{53F7}",
                    'input' => 'text',
                    'maxlength' => 128,
                    'hint' => "\u{586B}\u{5546}\u{6237} API \u{8BC1}\u{4E66}\u{5E8F}\u{5217}\u{53F7}\u{3002}",
                ],
                [
                    'key' => 'private_key',
                    'label' => "\u{5546}\u{6237}\u{79C1}\u{94A5}",
                    'input' => 'textarea',
                    'rows' => 8,
                    'secret' => true,
                    'hint' => "\u{586B}\u{4E0A}\u{4F20}\u{7684} apiclient_key.pem \u{5185}\u{5BB9}\u{3002}",
                ],
                [
                    'key' => 'platform_certificate',
                    'label' => "\u{5FAE}\u{4FE1}\u{652F}\u{4ED8}\u{5E73}\u{53F0}\u{8BC1}\u{4E66}/\u{516C}\u{94A5}",
                    'input' => 'textarea',
                    'rows' => 8,
                    'secret' => true,
                    'hint' => "\u{586B}\u{5FAE}\u{4FE1}\u{652F}\u{4ED8}\u{5E73}\u{53F0}\u{8BC1}\u{4E66}\u{6216}\u{5FAE}\u{4FE1}\u{652F}\u{4ED8}\u{516C}\u{94A5}\u{3002}",
                ],
            ],
            'payment_methods' => ['scan'],
            'payment_scenes' => ['general'],
            'default_payment_method' => 'scan',
            'default_payment_scene' => 'general',
        ],
    ],

    'alipay' => [
        'enabled' => filter_var(env('ALIPAY_ENABLED', false), FILTER_VALIDATE_BOOL),
        'app_id' => env('ALIPAY_APP_ID'),
        'public_key' => env('ALIPAY_PUBLIC_KEY'),
        'private_key' => env('ALIPAY_PRIVATE_KEY'),
        'gateway' => env('ALIPAY_GATEWAY', 'https://openapi.alipay.com/gateway.do'),
        'charset' => 'UTF-8',
        'sign_type' => 'RSA2',
        'version' => '1.0',
        'timeout_express' => '15m',
        'status_poll_interval_ms' => (int) env('ALIPAY_STATUS_POLL_INTERVAL_MS', 5000),
    ],

    'wechat' => [
        'enabled' => filter_var(env('WECHATPAY_ENABLED', false), FILTER_VALIDATE_BOOL),
        'app_id' => env('WECHATPAY_APP_ID'),
        'mch_id' => env('WECHATPAY_MCH_ID'),
        'api_v3_key' => env('WECHATPAY_API_V3_KEY'),
        'serial_no' => env('WECHATPAY_SERIAL_NO'),
        'private_key' => env('WECHATPAY_PRIVATE_KEY'),
        'platform_certificate' => env('WECHATPAY_PLATFORM_CERTIFICATE'),
        'gateway' => env('WECHATPAY_GATEWAY', 'https://api.mch.weixin.qq.com'),
        'currency' => env('WECHATPAY_CURRENCY', 'CNY'),
        'timeout_minutes' => (int) env('WECHATPAY_TIMEOUT_MINUTES', 15),
        'status_poll_interval_ms' => (int) env('WECHATPAY_STATUS_POLL_INTERVAL_MS', 5000),
    ],
];
